### ISSUE TITLE
SQL error running sprint status

### ISSUE THREAD

**Issue by cwarwicker** [writer-bot/bot#37]
```
[2023-01-20 06:54:58][INFO] user 765126981872123916 called sprint in server 1035641333089574973
{"options":[{"name":"status","type":1,"options":[]}],"uuid":"fed3a706-6071-4f39-be49-c034a828743e"}
```

```
{"uuid":"fed3a706-6071-4f39-be49-c034a828743e","stack":"SqlError: Parameter at position 1 is undefined\nSELECT * FROM projects WHERE id = ? - parameters:[undefined]\nsql: SELECT * FROM projects WHERE id = ? - parameters:[undefined]\n    at module.exports.createError (/app/node_modules/mariadb/lib/misc/errors.js:57:10)\n    at Query.throwUnexpectedError (/app/node_modules/mariadb/lib/cmd/command.js:40:24)\n    at Query.throwNewError (/app/node_modules/mariadb/lib/cmd/command.js:70:22)\n    at Query.validateParameters (/app/node_modules/mariadb/lib/cmd/query.js:176:14)\n    at Query.start (/app/node_modules/mariadb/lib/cmd/query.js:54:17)\n    at Connection.addCommandEnablePipeline (/app/node_modules/mariadb/lib/connection.js:1055:11)\n    at Connection.query (/app/node_modules/mariadb/lib/connection.js:1289:10)\n    at new Promise (<anonymous>)\n    at ConnectionPromise.query (/app/node_modules/mariadb/lib/connection-promise.js:87:12)\n    at DB._build_get (/app/src/classes/database.js:71:38)"}
```

Looks like its assuming a project exists for the sprint_user where there isn't one.

**Comment by cwarwicker** [comment]
Unable to replicate so far
