### ISSUE TITLE
Error running sprint wc

### ISSUE THREAD

**Issue by cwarwicker** [writer-bot/bot#38]
```
[2023-01-20 04:56:53][INFO] user 343564229669945356 called sprint in server 1055897168889774200
{"options":[{"name":"wc","type":1,"options":[{"name":"amount","type":4,"value":5517}]}],"uuid":"ecbcc59f-d170-4593-bb3f-053883f9561a"}
```

```
{"uuid":"ecbcc59f-d170-4593-bb3f-053883f9561a","stack":"TypeError: Cannot create property 'current_wc' on boolean 'false'\n    at Sprint.updateUser (/app/src/classes/sprint.js:554:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Sprint.setUserWordCount (/app/src/classes/sprint.js:624:13)\n    at async Object.execute (/app/src/commands/writing/sprint.js:203:20)\n    at async Client.<anonymous> (/app/src/bot.js:59:9)"}
```

Looks like sprint_user record is somehow missing or empty?

**Comment by cwarwicker** [comment]
Unable to replicate so far
